### PR TITLE
Adding multiparty threshold ECDSA

### PR DESCRIPTION
**Pull request by ghost**
There is a [working implementation](https://github.com/KZen-networks/multi-party-ecdsa) already, though more research is required [no security proof as of now, I believe]

### CODE REVIEW

**Comment by dr-orlovsky** [comment]
For more than 2-of-2 it is very challenging and really hard to implement. Why not to use Schnorr's instead?

**Comment by JonathanLogan** [comment]
Question: Is there a _blind_ and _untraceable_ threshold signature scheme out there that is sane? Because we would have to tick all three of blind, untraceable and threshold for it to make sense at all, and it should not require coordination on signature generation either. I don't see that done with any scheme right now, but I might be missing something.

**Comment by JonathanLogan** [comment]
Setup for big n's is too complicated for now. Gonna drop this until we have reached freeze of v1.

**Comment by dr-orlovsky** [comment]
> Question: Is there a blind and untraceable threshold signature scheme out there that is sane? 

Replying to your question, it seems that Schnorrs can do blind signatures https://github.com/sipa/bips/blob/bip-schnorr/bip-schnorr.mediawiki#Blind_Signatures however it looks like to be an imperfect one...

**Comment by ghost** [comment]
@JonathanLogan check out [this paper](https://arxiv.org/pdf/1802.07344.pdf) on selective  disclosure  credentialscheme  supporting  distributed  threshold  issuance,  public  andprivate attributes, re-randomization, and multiple unlinkable se-lective attribute revelations.


photo_2019-11-24_17-38-11

**Comment by JonathanLogan** [comment]
Thank you

**Pull request closed without merging**
